# Site settings
title: Sean Reilly
email: sean@seanreilly.net
description: "Digital Marketing Consultant"
baseurl: ""
url: "https://www.seanreilly.net"
github_username:  seanreillyesq
facebook_username:
linkedin_username: seanreillyesq

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
exclude: ["less","node_modules","README.md","Gemfile","Gemfile.lock"]
permalink: /:title-:year:month:day

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-archives
  - jekyll-last-modified-at
  - jekyll-paginate-v2

# Pagination (v2)
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title'
  sort_field: 'date'
  sort_reverse: true

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /category/:name/
    tag: /tag/:name/

# hreflang domains
hreflang_domains:
  default: "https://www.seanreilly.net"
  en-GB: "https://www.seanreilly.uk"
  en-IE: "https://www.seanreilly.ie"
  en-EU: "https://www.seanreilly.eu"
  it-IT: "https://www.powergenitalia.it"
